debian_task:
    test_script: make CC=gcc test
    container:
        dockerfile: Dockerfile

osx_task:
    test_script: brew install libmagic && make
    osx_instance:
        image: mojave-xcode-10.2

freebsd_task:
    test_script:
        - .ci/bsd.sh
        - sudo -u www BUILD_DIR=/var/www/html PATH="/usr/local/libexec/bats-core:$PATH" gmake test-minimal
    freebsd_instance:
        image: freebsd-12-0-release-amd64
