debian_task:
    test_script: make CC=gcc test
    container:
        dockerfile: Dockerfile

osx_task:
    test_script: make
    osx_instance:
        image: mojave-xcode-10.2

freebsd_task:
    test_script: make
    freebsd_instance:
        image: freebsd-12-0-release-amd64
